Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -18,26 +18,21 @@ phases:
   build:
     commands:
       - echo Building Docker image...
-      - |
-        if docker build -t $IMAGE_REPO_NAME:$COMMIT_ID $CODEBUILD_SRC_DIR && \
-           docker tag $IMAGE_REPO_NAME:$COMMIT_ID $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$COMMIT_ID; then
-          export BUILD_SUCCESS="true"
-        else
-          export BUILD_SUCCESS="false"
-        fi
+      - docker build -t $IMAGE_REPO_NAME:$COMMIT_ID $CODEBUILD_SRC_DIR
+      - docker tag $IMAGE_REPO_NAME:$COMMIT_ID $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$COMMIT_ID
+      - export BUILD_SUCCESS="true"
+      
 
   post_build:
     commands:
       - echo "Build success flag... $BUILD_SUCCESS"
-      - if [ "$BUILD_SUCCESS" = "true" ]; then
-          echo Pushing Docker image to ECR...
-          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$COMMIT_ID;
-          echo Writing image definitions file...
-          printf '[{"name":"nginx","imageUri":"%s"}]' $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$COMMIT_ID > imagedefinitions.json;
-          cat imagedefinitions.json;
-        else
-          echo "Build failed. Skipping Docker push and image definition creation."
-        fi
+      - if [ "$BUILD_SUCCESS" != "true" ]; then echo "Build failed, skipping post_build"; exit 1; fi
+
+      - echo Pushing Docker image to ECR...
+      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$COMMIT_ID;
+      - echo Writing image definitions file...
+      - printf '[{"name":"nginx","imageUri":"%s"}]' $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$COMMIT_ID > imagedefinitions.json;
+      - cat imagedefinitions.json
 
 artifacts:
   files:
